{{- if .Values.secrets.enabled }}
  {{- $serviceName := .Values.service.name -}}
  {{- $annotations := .Values.secrets.config.annotations -}}
  {{- $amnicRevision := .Values.amnic.revision -}}
{{- range $secretstore := .Values.secrets.config.secret }}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{$serviceName}}-es-{{lower $secretstore.type}}-{{$secretstore.region}}
  annotations:
    amnicRevision: {{ $amnicRevision | quote }}
    amnicUpdatedAt: {{ now | unixEpoch | quote }} {{- if $annotations }} {{ toYaml $annotations | nindent 4 }} {{- end }}
spec:
  refreshInterval: 0s
  secretStoreRef:
    name: {{$serviceName}}-ss-{{lower $secretstore.type}}-{{$secretstore.region}}
    kind: SecretStore
  target:
    name: {{$serviceName}}-secret-{{lower $secretstore.type}}-{{$secretstore.region}}
    creationPolicy: Owner
  data:
  {{- range $keys := $secretstore.keys }}
  - secretKey: {{$keys.key}}
    remoteRef:
      key: {{$keys.remoteKey}}
  {{- end }}
{{- end }}
{{- end }}

