{{- if .Values.secrets.enabled }}
  {{- $serviceName := .Values.service.name -}}
{{- range $secretstore := .Values.secrets.config.secret }}
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
  name: {{$serviceName}}-ss-{{lower $secretstore.type}}-{{$secretstore.region}}
spec:
  provider:
    aws:
      service: {{$secretstore.type}}
      region: {{$secretstore.region}}
      auth:
        jwt:
          serviceAccountRef:
            name: {{$serviceName}}
{{- end }}            
{{- end }}